apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:argo-events-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default:argo-events
subjects:
- kind: ServiceAccount
  name: argo-events
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default:argo-events
  namespace: default
rules:
# Allow everything for sensors
- apiGroups: ['argoproj.io']
  resources: ['sensors']
  verbs: ['*']
# Allow reading secrets and configmaps
- apiGroups: ['']
  resources: ['secrets', 'configmaps']
  verbs: ['get', 'list', 'watch']
# Triggering workflows
- apiGroups: [argoproj.io']
  resources: ['workflows']
  verbs: ['create', 'update', 'patch', 'delete']
