# The sensor controller configmap includes configuration information for the sensor controller
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-controller-configmap
  namespace: default
data:
  config: |
    namespace: default
    instanceID: axis
